default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  host: host.docker.internal
  database: chapiko_db
  username: root
  password:

production:
  <<: *default
  database: chapiko_db_production
  host: <%= Rails.application.credentials.chapiko_db_host %>
  username: <%= Rails.application.credentials.chapiko_db_username %>
  password: <%= Rails.application.credentials.chapiko_db_password %>
