default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: chapiko_db
  username: root
  password:

production:
  <<: *default
  database: db/production.sqlite3
